from __future__ import annotations

import amulet.utils.signal

__all__ = ["SignalTest"]

class SignalTest:
    def __init__(self) -> None: ...
    def emit(self) -> None: ...
    @property
    def signal_0(self) -> amulet.utils.signal.Signal[()]: ...
    @property
    def signal_1(self) -> amulet.utils.signal.Signal[int]: ...
    @property
    def signal_2(self) -> amulet.utils.signal.Signal[int, float]: ...
    @property
    def signal_3(self) -> amulet.utils.signal.Signal[int, float, str, int]: ...
