from __future__ import annotations

__all__: list[str] = ["bytes_passthrough", "get_bytes", "get_len", "test_cpp"]

def bytes_passthrough(arg0: bytes) -> bytes: ...
def get_bytes() -> bytes: ...
def get_len(arg0: bytes) -> int: ...
def test_cpp() -> None: ...
