from __future__ import annotations

import amulet.utils.event

__all__: list[str] = ["EventTest"]

class EventTest:
    def __init__(self) -> None: ...
    def dispatch(self) -> None: ...
    @property
    def event_0(self) -> amulet.utils.event.Event[()]: ...
    @property
    def event_1(self) -> amulet.utils.event.Event[int]: ...
    @property
    def event_2(self) -> amulet.utils.event.Event[int, float]: ...
    @property
    def event_3(self) -> amulet.utils.event.Event[int, float, str, int]: ...
